---
- hosts: localhost
  user: mladen
  connection: local

  vars_files: 
    - vars/main.yml

  tasks:
    - name: Add homebrew taps
      homebrew_tap: 
        name: "{{item.name}}"
        state: present
      with_items: homebrew_taps

    - name: Install Homebrew
      homebrew: 
        name: "{{item.name}}"
        state: present
        update_homebrew: yes
      with_items: homebrew_packages
