---
- hosts: localhost
  user: mladen
  connection: local

  vars_files:
    - vars/main.yml

  tasks:
    - include: tasks/install-apps.yml
    - include: tasks/dotfiles.yml
    - include: tasks/vim-configuration.yml
    - include: tasks/node.yml
    - include: tasks/osx.yml

