---

- name: Copy vimrc
  copy:
    src: files/vimrc
    dest: ~/.vimrc
  tags: vim

- name: Ensure vundle folder exists
  file:
    path: ~/.vim/bundle
    state: directory
  tags: vim

- name: Clone vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim
    update: true
    force: yes
  tags: vim

- name: Start vim for the first time
  command: vim +PluginInstall +qall
  tags: vim

