#load antigen bundle manager
source /usr/local/Cellar/antigen/1/share/antigen.zsh

antigen-use oh-my-zsh

# load plugins
antigen bundle git
antigen bundle node
antigen bundle npm
antigen bundle zsh-users/zsh-completions src
antigen bundle zsh-users/zsh-syntax-highlighting
antigen-bundle zsh-users/zsh-history-substring-search
antigen bundle vundle

antigen-theme jreese

antigen-apply

# source nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm

# initialize thefuck
eval $(thefuck --alias)

autoload -U colors && colors
setopt promptsubst

